title:              Li Yijuan | 李懿娟
email:              serenalyjuan@gmail.com
description:        Freelance Writer | 自由作者
author:             Li Yijuan
baseurl:            "/LL"
url:                "https://proskahn.github.io/LL"

# Social Profiles
twitter_username:   serena_lyjuan?t=RVuhMMCMiPkaru_oVax0pA&s=09
facebook_username:  profile.php?id=100089759058416&mibextid=9R9pXO 
linkedin_username:  yijuan-li-1a9634227?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
